version: '3.7'

services:

  client:
    build:
      context: ./client
    ports:
      - 80:8080
    environment:
      - HOME=/client
  
  server:
    build:
      context: ./server
    ports:
      - 3031:3031
